services:
  backend:
    image: online-store-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app  # Optional: for live code reloads (host folder → container)
    working_dir: /app
    command: ["node", "index.js"]
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASS: admin123
      DB_NAME: online_store

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: online_store
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: