services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=dev # This sets the env variable inside the container
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASS=admin123
      - DB_NAME=online_store
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app # Mount your host backend directory to /app in the container
      - /app/node_modules # Anonymous volume for node_modules
    command: npm run dev # Explicitly tell Docker Compose to run nodemon
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: online_store

volumes:
  pgdata: